apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: infrastructure-manager-le-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: infrastructure-manager
    app.kubernetes.io/part-of: infrastructure-manager
    app.kubernetes.io/managed-by: kustomize
  name: infrastructure-manager-le-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
- kind: ServiceAccount
  name: infrastructure-manager
  namespace: system
