apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: infrastructure-manager-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: infrastructure-manager
    app.kubernetes.io/part-of: infrastructure-manager
    app.kubernetes.io/managed-by: kustomize
  name: infrastructure-manager
  namespace: system
